CREATE TABLE Cliente
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128),
    credito DOUBLE PRECISION
)


CREATE TABLE Venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128),
    credito DOUBLE PRECISION
)


CREATE TABLE Oggetti
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    prezzo DOUBLE PRECISION,
    pezzi INTEGER,
    descrizione VARCHAR(200),
    url VARCHAR(600),
    idVenditore INTEGER,
    FOREIGN KEY (idVenditore) REFERENCES Venditore(id)
)


INSERT INTO Venditore(id, nome, cognome, username, password, credito)
VALUES (default, 'Alessandro', 'Del Piero', 'delpiero', '10', 1000.00),
       (default, 'Zinedine', 'Zidane', 'zidane', '11', 300.00 );


INSERT INTO Cliente(id, nome, cognome, username, password, credito)
VALUES (default, 'Fabrizio', 'Cara', 'fabrizio', '12', 1000.00),
       (default, 'Dino', 'Baggio', 'baggio', '1', 500.00 );


INSERT INTO Oggetti (id, nome, prezzo, pezzi, descrizione, url, idVenditore)
VALUES (default, 'HP SPECTRE X360 13-4112NL', 1499.00, 30, '', 'images/FotoHPSPECTREX36013-4112NL.jpg', 1),
       (default, 'MITSUBISHI MUZ-HJ35VA', 519.99, 15, '', 'images/FotoMITSUBISHIMUZ-HJ35VA.jpg', 1),
       (default, 'SAMSUNG SM-G930 Galaxy S7 32 GB Gold', 729.00, 1, '', 'images/FotoSAMSUNGSM-G930GalaxyS732GBGold.jpg', 1),
       (default, 'SAMSUNG AddWash WW80K6414QW', 799.00, 120, '', 'images/FotoSAMSUNGAddWashWW80K6414QW.jpg', 1),
       (default, 'CANON EOS 700D Kit 18-55 e 55-250', 949.00, 86, '', 'images/FotoCANONEOS700DKit18-55e55-250.jpg', 2),
       (default, 'MITSUBISHI MUZ-HJ35VA', 820.99, 15, '', 'images/FotoMITSUBISHIMUZ-HJ35VA.jpg', 2),
       (default, 'SAMSUNG SM-G930 Galaxy S7 32 GB Gold', 600.00, 1, '', 'images/FotoSAMSUNGSM-G930GalaxyS732GBGold.jpg', 2);